#!/usr/bin/env bash

set -e
set -u

root_dir=$(readlink -e $(dirname $0))
config_dir=$root_dir/config

mkdir -p $config_dir
cd $root_dir

git submodule update --init --recursive

bash main4ino-server/misc/scripts/configgen/update
cp -f src/main/resources/defaultconfig/* $config_dir
cp -f main4ino-server/misc/scripts/configgen/security.conf $config_dir

sbt -Dconfig-dir=$config_dir 'runMain org.mauritania.main4ino.Server' &

cd $root_dir/botino-arduino
./.mavarduino/create_links
sleep 10
./simulate profiles/simulate.prof
